### ISSUE TITLE
Does not re-hide/close after opening via hotkey 

### ISSUE THREAD

**Issue by tecandrew** [MatthiasGrandl/Loungy#32]
Spotlight and Alfred both close and return to the window you had active prior to invoking their hotkey. Would be great if Loungy does this as well 😃

**Comment by MatthiasGrandl** [comment]
Can you elaborate on the behavior you are missing? When I close Loungy with Esc and then reopen with the hotkey, it takes me back to the screen I was on prior to closing. There is however a timer which resets the screen back to the root screen after 90 seconds.

**Comment by tecandrew** [comment]
https://github.com/MatthiasGrandl/Loungy/assets/21319730/5ff80ada-710a-428a-bef8-85d6e86ae75d

The ability to hide or exit Loungy using the same hotkey to open it like the example video. Both Spotlight and Alfred have this behavior. I can exit using `ESC` just fine, but would be nice to hide using the same hotkey

interesting find too:

the KeyCaster app i use to record key presses doesn't show the keys when I'm within Loungy 🤔 (end of video)

**Comment by MatthiasGrandl** [comment]
Ah ok I get it! Yeah should be no problem to fix. Didn’t consider some people using the same hotkey to toggle their launcher. I always just ESC. 

Regarding the keys not showing while in Loungy, I assume it’s because it’s not a native input field? Not sure how I would go about fixing it. Does it work in the Zed editor?

**Comment by tecandrew** [comment]
yep! seems to work in the Zed editor. strange behavior that Loungy doesn't register these clicks

https://github.com/MatthiasGrandl/Loungy/assets/21319730/4341a07e-76d0-4937-badd-e47dd8531a75

**Comment by MatthiasGrandl** [comment]
I implemented this. Was a bit more work than expected, because I had to add some state tracking which command is currently running in the foreground. For example:

- I have the clipboard manager open with hotkey (Hyper+V), I want it to close by using the same hotkey.
- If I have the root view open and then use the clipboard manager hotkey, I want it to open the clipboard manager and not close the window.

Should be working nicely now.

**Comment by tecandrew** [comment]
nice! I'll keep a lookout on GH and Brew releases!

**Comment by MatthiasGrandl** [comment]
> nice! I'll keep a lookout on GH and Brew releases!

I still have to fix the release pipeline. MacOS notarization broke somehow and it's impossible to debug :(

**Comment by MatthiasGrandl** [comment]
It's released now, albeit without notarization, so MacOS might complain about Loungy being untrusted.
