### ISSUE TITLE
Happy to see a pure rust implementation

### ISSUE THREAD

**Issue by ParthJadhav** [MatthiasGrandl/loungy#9]
Hey there, 

I am quite excited to see this pure rust alternative of Raycast & Spotlight. I read the readme and figured out that you used Tauri at start but found it quite tedious. 

I've built one in Tauri already. I just thought you would be interested to check it out. 

https://github.com/ParthJadhav/Verve

**Comment by MatthiasGrandl** [comment]
nice that looks cool! will have to dig into it a bit. I also converted icns to png in rust, but decided to go the swift-rs route because that way it was easier to get proper application names and also system setting icons, which wasn't possible without swift.

I also used Svelte for my Tauri prototype so I guess great minds think alike :)

**Comment by ParthJadhav** [comment]
> nice that looks cool! will have to dig into it a bit.

Thanks 😄 

> I also converted icns to png in rust, but decided to go the swift-rs route because that way it was easier to get proper application names and also system setting icons, which wasn't possible without swift.

Yep, I faced the same problem. I just downloaded the icons I wasn't able to convert and added them as direct resources.

![CleanShot 2024-02-10 at 13 26 02@2x](https://github.com/MatthiasGrandl/loungy/assets/42001064/fe6eaba6-b322-42d6-8c92-bebf4075adb4)

> I also used Svelte for my Tauri prototype so I guess great minds think alike :)

Haha, It was quite easy to work with Svelte in this case.
